spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}-${HOSTNAME}
  client:
    service-url:
      defaultZone: http://eureka-server-zone-1:8761/eureka/,http://eureka-server-zone-2:8761/eureka/
logging:
  level:
    com.netflix: debug