spring:
  application:
    name: demo-client
eureka:
  instance:
    instance-id: ${spring.application.name}-${ZONE}-${HOSTNAME}
  client:
    service-url:
      defaultZone: http://eureka-server-zone-2:8761/eureka/,http://eureka-server-zone-1:8761/eureka/
logging:
  level:
    com.netflix: debug