spring:
  application:
    name: eureka-server-zone-1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-zone-1:8761/eureka/
  instance:
    hostname: eureka-server-zone-2
    appname: demo-eureka-server
  server:
    enable-self-preservation: false
server:
  port: 8761